Remove the empty confusing Account section from setting page.
wuethrich44/flarum-ext-sso pull request #2
Opened 2017-08-02 20:22 UTC by zinsserzh

2017-08-04 22:20 UTC, fabwu requested changes

2017-08-04 22:20 UTC, wuethrich44 commented on js/forum/dist/extension.js
> +                    if (items.has('account')) {
This looks a little bit too complicated to me. Either remove the complete account section or check if there are any children and remove them like this:
```javascript
if (items.get('account').props.children.length === 0) {
    items.remove('account')
}
```

2017-08-04 22:20 UTC, wuethrich44 commented on js/forum/dist/extension.js
>                      items.remove('changeEmail');
If you remove the whole account section you can get rid of these function but if future releases add more options to the account section you're not safe 😕

2017-08-04 22:51 UTC, zinsserzh commented on js/forum/dist/extension.js
>                      items.remove('changeEmail');
No, I'm not simply removing the entire section. The new function is triggered after your `removeProfileActions` function. I check if it is empty. If so, remove, if not, do nothing.

2017-08-04 23:00 UTC, zinsserzh commented on js/forum/dist/extension.js
> +                    if (items.has('account')) {
I submitted a PR https://github.com/flarum/core/pull/1218 to add the `isEmpty()` utility to ItemList. I added the part to check if it is implemented to make sure it is compatible with the current flarum beta7 release. After the PR is added into flarum's core release, the emulation part can be removed. Plus, `ItemList` does not have `props` attribute. My current implementation is the best way I know to [check if an object is empty]( https://stackoverflow.com/questions/679915/how-do-i-test-for-an-empty-javascript-object)

2017-08-06 15:39 UTC, wuethrich44 commented on js/forum/dist/extension.js
> +                    if (items.has('account')) {
I've tested the code above and it works fine in my case. I just don't want to add 20 lines of code only to remove a simple heading. Do you like to simplify this or should we wait until https://github.com/flarum/core/pull/1218 is merged?

2017-08-10 07:03 UTC, merged

2017-08-10 07:04 UTC, wuethrich44 commented
@zinsserzh Thanks for this PR. As soon as your flarum core PR is ready I will change the code.

2017-08-10 14:33 UTC, zinsserzh commented
Actually this does not rely on the core PR. My previous implementation is wrong. This code is good to go.